### ISSUE TITLE
Searching 'Umbellula' in the WoRMS api using fathomnet-py failure.

### ISSUE THREAD

**Issue by asw-v4** [fathomnet/community-feedback#206]
### Example usage:

```
import fathomnet.api.worms as worms
node = worms.get_info('Umbellula')
```
### Expected Behaviour:

Returns node from endpoint.

### Actual Behaviour - 404 Error:
```
REQUEST:
    Method: GET
    URL: https://database.fathomnet.org/worms//taxa/info/Umbellula
    Headers:
        User-Agent: python-requests/2.32.3
    Accept-Encoding: gzip, deflate, br, zstd
    Accept: */*
    Connection: keep-alive

    Body:
    None

RESPONSE:
    Status: 404
    Headers:
        Server: nginx/1.14.1
    Date: Sun, 06 Apr 2025 17:13:09 GMT
    Content-Type: application/json
    Content-Length: 51
    Connection: keep-alive
    Content:
    b'{"message":"Unable to find `Umbellula`","code":404}'
```

### Workaround:
**Substitute: `Umbellula` for `Umbellula 2`**

### Note:
Interestingly, on the Fathomnet Database - Umbellula returns results, `whereas Umbellula 2` does not (But is listed explicitly as a searchable term in the search box)
